config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "about", to: "about#index"

  # get "/", to: "main#index"
  # same as
  root to: "main#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
   attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
# 
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_login!
        redirect_to sign_in_path, alert: "You must be signed in to do that" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_later
        end
        redirect_to root_path, notice: "If an account with that email was found, we have sent an email"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired. Please try again"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset sucessfully. Please sign in."
        else
            render :edit
        end
    end

    private 
    
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_login!
    
    def edit 
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated!"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "User created"            
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> About us </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ScheduledTweet</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    </head>

    <body>
        <%= render partial: "shared/navbar" %>
        <div class="container">
            <%= render partial: "shared/flash" %>
            <%= yield %> 
        </div>
    </body>
</html>

app/views/main/index.html.erb
<div class= "d-flex align-items-center justify-content-center ">
    <h1> Welcome to Scheduled Tweets </h1>
</div>

app/views/password_resets/edit.html.erb
<h1> Reset your password? </h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger"> 
            <% form.object.errors.full_messages.each do |message| %>
                <div> 
                    <%= message %>
                </div>
            <% end %>
        </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control", placeholder: "teste@123" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "teste@123" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Reset password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1> Forgot your password? </h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email, class: "form-label" %>
        <%= form.text_field :email, class: "form-control", placeholder: "thiagomrvieira@gmail.com" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Reset password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div> 
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to "Navbar", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mg-lg-0">
                <% if Current.user %>
                    <li class="nav-item">
                        <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
                    </li>    
                    <li class="nav-item">
                        <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-secondary" %>
                    </li>    
                <% else %>
                    <li class="nav-item">
                        <%= link_to 'Login', sign_in_path, class: "nav-link" %>
                    </li>    
                    <li class="nav-item">
                        <%= link_to 'Sign up', sign_up_path, class: "nav-link" %>
                    </li>    
                <% end %>
            </ul>
        </div>

    </div>
</nav>